In [44]:
#Importing Packages
import requests
import pandas as pd
from datetime import datetime

In [45]:
# fucntion to get data for etherium function
def get_eth_market_chart(vs_currency='usd', days='30'):
    url = f'https://api.coingecko.com/api/v3/coins/ethereum/market_chart'
    params = {'vs_currency': vs_currency, 'days': days}
    response = requests.get(url, params=params)
    data = response.json()
    
    prices = data['prices']
    df = pd.DataFrame(prices, columns=['timestamp', 'price'])
    df['date'] = pd.to_datetime(df['timestamp'], unit='ms')
    return df

In [46]:
#Etherium data
eth_data=get_eth_market_chart()
eth_data.head()

       timestamp        price                    date
0  1744902291831  1571.301180 2025-04-17 15:04:51.831
1  1744905869456  1583.710427 2025-04-17 16:04:29.456
2  1744909336252  1604.454461 2025-04-17 17:02:16.252
3  1744913172023  1611.523371 2025-04-17 18:06:12.023
4  1744916853592  1603.308512 2025-04-17 19:07:33.592

In [47]:
def convert_to_ohlc(df):
    df.set_index('date', inplace=True)
    ohlc = df['price'].resample('1D').ohlc()
    return ohlc.dropna()

In [48]:
ohlc=convert_to_ohlc(eth_data)
ohlc.head()

                   open         high          low        close
date
2025-04-17  1571.301180  1611.523371  1571.301180  1584.318058
2025-04-18  1583.445591  1597.187925  1578.793171  1593.265053
2025-04-19  1589.038303  1619.973514  1586.456621  1618.448076
2025-04-20  1613.630199  1617.028701  1571.544554  1581.604081
2025-04-21  1586.331680  1649.244205  1571.389081  1577.052545

In [51]:
#plotting the candlesticks for 30 days data of etherium

import webbrowser

def plot_candlestick_to_browser(ohlc, filename='eth_candlestick.html'):
    import plotly.graph_objects as go
    
    fig = go.Figure(data=[go.Candlestick(
        x=ohlc.index,
        open=ohlc['open'],
        high=ohlc['high'],
        low=ohlc['low'],
        close=ohlc['close'],
        increasing_line_color='green',
        decreasing_line_color='red'
    )])
    
    fig.update_layout(
        title='Ethereum Price Candlestick Chart (30 Days)',
        xaxis_title='Date',
        yaxis_title='Price (USD)',
        xaxis_rangeslider_visible=False
    )
    
    # Save to HTML
    fig.write_html(filename)
    
    # Open in default web browser
    webbrowser.open_new_tab(filename)


plot_candlestick_to_browser(ohlc)